### ISSUE TITLE
Titles to Keyword doesn't support clips with conform-rate

### ISSUE THREAD

**Issue by galaxly5** [fcpxhacks/fcpxhacks#3162] opened 2022-12-06 06:39 UTC
This tool will generate the keywords, but not linked the connect clips in the browser, it doesn't link the clip range even when I drag the keywords in the Event afterwards there is not link with any clips just keywords with empty media.

**Comment by latenitefilms** [comment] 2022-12-06 06:47
The **Create Titles from Text** section is basically a helper tool, that you can use to easily create new titles. All it does is generate titles.

In terms of the **Titles to Keywords** tool, when you drag a Final Cut Pro Event to this Toolbox (which must only contain a single Project), we will look through all the Titles connected to the clips in the Primary Storyline, read the name of those clips (as they appear in the Timeline Index), then create new Keyword Ranges for each of those Titles, including any connected clips. We then send that data back into Final Cut Pro as a new Event with a ✅ prefix. This will happen automatically if you only have one library open, otherwise you'll be prompted to select a library to import it into.

Does that make sense?

**Comment by galaxly5** [comment] 2022-12-06 07:07
Hello, thanks for the really quick feed back so just to confirm it only generates keywords,  it doesn't link the keywords to any clips or clip ranges in the browser is that correct?

**Comment by latenitefilms** [comment] 2022-12-06 07:14
The **Create Titles from Text** section will just generate titles:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/22286696/205844785-978cfcc9-da73-45ec-a3b2-339b4f1dd8c4.png">

The **Titles to Keywords** section will convert titles to keyboard.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/22286696/205844860-c58fd951-9221-4f4a-9eb1-2ba46c4ea778.png">

For example... before:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/22286696/205845481-9e3e194c-792b-49d2-9688-e7cb515de033.png">
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/22286696/205845482-d3c0a225-c862-40b4-a0fa-4c0b0fc3e82e.png">

...after:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/22286696/205845587-a6bee070-191a-4ea5-a383-713b3654f26e.png">

**Comment by galaxly5** [comment] 2022-12-06 07:17
Okay so when you click on the keywords, Test A, Test B, Test C will it be empty 
in the browser.

**Comment by latenitefilms** [comment] 2022-12-06 07:42
No, those keywords will be applied:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/22286696/205850726-c411bb8c-af8b-4899-820c-c9144fb7bb4d.png">
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/22286696/205850736-4eada6ee-b507-489e-a002-adb68d21fd65.png">
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/22286696/205850766-2e686401-30d2-4031-86b1-43618d9a0cd6.png">

**Comment by latenitefilms** [comment] 2022-12-06 07:43
You can also see in the above screenshots that **Test A** has been favourited and **Test B** has been rejected.

**Comment by galaxly5** [comment] 2022-12-06 07:58
Okay Chris,

So when I do it, I have the keywords but no clips, it's empty. Either I must be doing something wrong or it's bugged somehow

![image](https://user-images.githubusercontent.com/36759827/205853867-727e7b03-6bc6-41ce-b3e9-482038072133.png)

**Comment by galaxly5** [comment] 2022-12-06 08:05
Unless it's a bug for apple silicon based Mac  final cut pro as opposed to intel based Mac Final Cut Pro.  I know they had had issue with Keyflow Pro importing keywords in but not linked to any clips, but they have fixed that in the latest update for apple silicon.

**Comment by latenitefilms** [comment] 2022-12-06 08:07
Can you share a screenshot of what the timeline/project looks like? Is there only a single timeline/project in the event you're dragging? If you try reproduce the above does it work for you?

Feel free to email me a FCPXML or Library if you're still having issues. You can send feedback via the CommandPost menubar and include error logs.

**Comment by latenitefilms** [comment] 2022-12-06 08:10
The above tests were done on an Apple Silicon MacBook Pro, so that shouldn't be an issue. I'm on Monterey though, so it's possible it could be a Ventura bug - but unlikely, as this just uses FCPXML so it should be consistent across macOS releases.

**Comment by galaxly5** [comment] 2022-12-06 08:45
No worries Christ let me create a project and do

> Can you share a screenshot of what the timeline/project looks like? Is there only a single timeline/project in the event you're dragging? If you try reproduce the above does it work for you?
> 
> Feel free to email me a FCPXML or Library if you're still having issues. You can send feedback via the CommandPost menubar and include error logs.


Thanks Chris, yes I followed the instruction and created a single timeline in a single event then dragged into Command Post.  I'll replicate it again and email you.  Thanks again for you help.

**Comment by galaxly5** [comment] 2022-12-06 08:47
What's your email Chris? I recored it and have the Final Cut File I can send you

**Comment by latenitefilms** [comment] 2022-12-06 08:50
Email: team at commandpost dot io

**Comment by galaxly5** [comment] 2022-12-06 08:52
okay great you'll get an email from Jake Jones cheers mate

**Comment by latenitefilms** [comment] 2022-12-06 10:50
I'm GUESSING that this probably has something to do with the fact you have 50p clips in a 24p timeline.

I need to do some more digging, but I'm assuming we're just not handling the maths right.

Note to self: https://developer.apple.com/documentation/professional_video_applications/fcpxml_reference/story_elements/conform-rate

**Comment by galaxly5** [comment] 2022-12-06 11:11
Hi Christ I just tried on a different project altogether, 24p on 24p timeline still same results, the keywords are empty.

**Comment by latenitefilms** [comment] 2022-12-06 11:31
Ah, I missed something very obvious... the media also needs to be in the event you're dragging. If there's no media in the event, then obviously it can't keyword the media.

I'm still not entirely sure how the maths will work if you have 50p clips in a 24p timeline - it's possible it might just work, or it's possible things won't line up perfectly because we're not accounting for the conform rate, but if you have 50p clips, you're better off with a 25p or 50p project/timeline anyway, then that should work as expected.

With your test library, if I just drag all the Day 1 footage into the Test event, it works as expected. However, again, I think if all your clips are 50p, I would create a new 50p timeline to rule out any conform rate issues. Also, note that if you copy clips with a conform rate into a new timeline, that conform settings will follow it, so you'll need to match frame and then replace to get rid of the conform rate options in the Inspector.

**Comment by galaxly5** [comment] 2022-12-09 12:34
Ah! Great I was moving the keywords into the old event thinking it was going to link the media, so I'll try it the other way around as you suggested see if it works.  Thanks heaps.

**Comment by galaxly5** [comment] 2022-12-09 12:52
Okay Christ very interesting, so before I run the command post toolbox titles to keywords I must move all the clips into the new event with a single project.  If I drag the keyword only into the old event it will only generate a the keyword or keywords (if more than one selected) with no clip attached.  However if I drag one clip from the newly created event (with tick) it will create the keywords with the associated clips with it, regardless of frame rate, works with Multicam clips.  Bit of a work around but it works, wow now this will save me so many hours.  Thanks so much Christ, where can I go to support what your guys are doing?

**Comment by latenitefilms** [comment] 2023-01-25 11:08
Apologies for the very delayed reply - I've been distracted with other projects.

You can learn more about sponsoring CommandPost here: https://commandpost.io/#sponsor

We're also gearing up to release [BRAW Toolbox](https://brawtoolbox.io) and [Gyroflow Toolbox](https://gyroflowtoolbox.io) on the Mac App Store.

I'll close this issue for now, as I think the problem is solved, but yell out if you have any questions!

**Closed as completed by latenitefilms** 2023-01-25 11:08 UTC
Labels: bug
