### ISSUE TITLE
Test if focus watchers are delaying app switching 

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#1089] opened 2018-03-20 21:50 UTC

**Comment by latenitefilms** [comment] 2018-03-21 03:07
@randomeizer - I've never noticed this issue. How can I reproduce?

**Comment by randomeizer** [comment] 2018-03-21 03:21
Get a slower computer?

**Comment by randomeizer** [comment] 2018-03-21 03:22
I often notice a delay when switching from the CP Error Log to FCP. For
example, I click on the FCPX menu bar, and there will be a 1-2 second delay
before it shows up the first time.

**Comment by latenitefilms** [comment] 2018-03-21 03:26
@randomeizer - Interesting! Well, I definitely can't reproduce that on my laptop - MacBook Pro (15-inch, 2017) running macOS 10.13.2. I can easily jump between the Error Log & Final Cut Pro with no lag or issues. If I have the Error Log in focus, then click the Final Cut Pro menu bar, Final Cut Pro will instantly get focus and the menu will open instantly. I wonder if it's a Sierra vs High Sierra thing or just a CPU speed thing?

**Comment by randomeizer** [comment] 2018-03-21 03:35
Not sure. I'd be interested to test what happens if we put the 'watch'
update functions in cp.apple.finalcutpro/init into timers, rather than just
calling the watchers directly. Not sure if it would make a big difference.

**Comment by latenitefilms** [comment] 2018-03-21 03:37
You know me, I love a good old `hs.timer` - go for it!

Really, we should try and make EVERYTHING in CommandPost non-blocking via callbacks and timers.

**Comment by randomeizer** [comment] 2018-03-25 11:32
"Non-blocking" is a bit of an illusion, given that everything runs on a
single thread, but yeah.

**Comment by latenitefilms** [comment] 2018-05-25 07:15
@randomeizer - Did you test this as part of #1156?

**Comment by latenitefilms** [comment] 2018-06-04 05:11
I'm not seeing any issues switching between apps, so I'm going to close this issue for now. Reopen if you disagree!

**Closed as completed by latenitefilms** 2018-06-04 05:11 UTC
Labels: bug
