### ISSUE TITLE
Shortcut key operation error

### ISSUE THREAD

**Issue by cdj0004** [fcpxhacks/fcpxhacks#3331] opened 2024-04-03 13:57 UTC
<img width="980" alt="스크린샷 2024-04-03 오후 10 53 50" src="https://github.com/CommandPost/CommandPost/assets/122513523/a455cf65-cc41-4fdd-ae9c-0867fe2686bb">
Final Cut Short Key Not Available
<img width="980" alt="스크린샷 2024-04-03 오후 10 53 50" src="https://github.com/CommandPost/CommandPost/assets/122513523/88e0a41f-c2cc-454a-a5a7-e3f83d329a7e">

**Comment by latenitefilms** [comment] 2024-04-04 02:33
What issue are you seeing exactly?

**Comment by cdj0004** [comment] 2024-04-04 03:03
If you set a shortcut to change the playback setting and press the shortcut, the shortcut does not work
I've tried changing the shortcut in various ways, but it doesn't work

Shortcuts that don't work are better playback performance , better playback quality 





-----Original Message-----

**Comment by latenitefilms** [comment] 2024-04-10 06:08
I think the issue is that you probably don't have these shortcut keys setup in your Final Cut Pro Command Editor? Basically all these actions do is trigger the keyboard shortcuts that are stored in your keyboard layout.

**Comment by latenitefilms** [comment] 2024-10-08 01:07
@cdj0004 - Are you still having this issue?

**Comment by latenitefilms** [comment] 2024-12-06 23:41
I'm going to close this issue for now, but feel free to re-open it if you're still having issues with the latest CommandPost release.

**Closed as completed by latenitefilms** 2024-12-06 23:41 UTC
Labels: bug, waiting on user feedback
