### ISSUE TITLE
Hacks Shortcuts still work when FCPX is not active

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#778] opened 2017-09-28 19:36 UTC

**Comment by latenitefilms** [comment] 2017-09-29 12:56
@randomeizer - I've tried to work this out, but I have no idea why it's not working.

If you have Hacks Shortcuts enabled (i.e. "Control CommandPost Shortcuts within Final Cut Pro" ticked), and you load CommandPost with Final Cut Pro open but NOT frontmost, the Hacks shortcuts will be enabled on load. For example, if you have the "A" key assigned to something in Final Cut Pro in this scenario, when you load CommandPost, you won't be able to use the "A" key in other applications, until you give Final Cut Pro focus and then go back to your original application.

This SHOULD be handled by `plugins.finalcutpro.commands` in `plugin.postInit()` - but it doesn't seem to work. 

I've also tried messing around with a few other things, but they didn't seem to work either.

I'll need your amazing problem solving ability for this one!

**Comment by randomeizer** [comment] 2017-10-02 07:59
This seems to be an issue with detecting when FCP is actually frontmost. There seem to be some quirks with the `hs.*.filter` modules which mean we don't always get a notification about the app loading/quitting/gaining focus when we expect. In particular, I've noticed this is the case when restarting FCPX.

**Comment by randomeizer** [comment] 2017-10-02 08:04
[logger.lua.zip](https://github.com/CommandPost/CommandPost/files/1348219/logger.lua.zip)

I've attached a plugin I made to log various events when CP/FCPX is gaining/losing focus, apps loading, etc. I haven't put this into the main branch because it would be disruptive to regular users, but if you put this in your `~/Library/Application Support/CommandPost/Plugins` folder, it will give you a message when we are detecting that focus changes. As you'll notice, there are some situations where it is not up-to-date (eg. changing FCPX language, forcing a restart).

I think one contributor is that CP doesn't have its own icon on the Dock. This is handy for keeping us unobtrusive, but it's a pain when we activate some UI element such as the Console, dialog boxes, etc.

Not sure what the solution is exactly, just need to figure out how we can check the 'focused' status more reliabily.

**Comment by latenitefilms** [comment] 2017-10-02 08:08
From memory, I think FCPX Hacks used `hs.window` to detect some events, but things like FCPX opening and closing were handled by `hs.application`.

**Comment by randomeizer** [comment] 2017-10-02 08:10
I'm using both `hs.window.filter` and `hs.application.filter` currently.

At the moment it's specifically looking for the 'FCPX' bundle ID to get filtered events, but there are some events that don't come through reliably when filtered that way (e.g. the application closing) - sometimes the event is still sent, but with a `nil` bundle ID, so it doesn't get through. I'll do some more testing and see if I can figure out a workaround.

**Comment by latenitefilms** [comment] 2017-10-02 08:12
What we could do is if we detect a window is created with the FCPX bundle ID, we could then store the window ID, and use that to detect when it's destroyed?

**Comment by randomeizer** [comment] 2017-10-02 08:36
I've added some extra checking, which seems to work pretty reliably on my machine. Can you do some testing?

**Comment by latenitefilms** [comment] 2017-10-02 08:47
It still has the same issue...

If you have Hacks Shortcuts enabled (i.e. "Control CommandPost Shortcuts within Final Cut Pro" ticked), and you load CommandPost with Final Cut Pro open but NOT frontmost, the Hacks shortcuts will be enabled on load. For example, if you have the "A" key assigned to something in Final Cut Pro in this scenario, when you load CommandPost, you won't be able to use the "A" key in other applications, until you give Final Cut Pro focus and then go back to your original application.

**Comment by latenitefilms** [comment] 2017-10-02 09:32
As discussed on Facebook:

> Basically, if Hacks Shortcuts are enabled, when you first load CommandPost, Hacks Shortcuts will ALWAYS be active, even if FCPX isn't active.

**Comment by randomeizer** [comment] 2017-10-03 00:53
Yeah, I can replicate the problem. Trying to pin down the cause.

**Comment by latenitefilms** [comment] 2017-10-03 02:13
Sweet, thanks mate!

**Comment by randomeizer** [comment] 2017-10-03 04:32
It doesn't seem to be dependent on having Hacks Shortcuts enabled. It does the same thing with CP-controlled shortcuts.

**Comment by randomeizer** [comment] 2017-10-03 06:50
Resolved by using 'isActive' in cp.commands.command rather than 'isEnabled', which doesn't take into account if the command is actually active at the present time (usually due to app focus)

**Closed as completed** 2017-10-03 06:50 UTC
Labels: bug
