### ISSUE TITLE
Background Render on FCPX interferes with Wave Panel

### ISSUE THREAD

**Issue by AndrewBrinsmead** [fcpxhacks/fcpxhacks#2231] opened 2020-01-11 06:25 UTC
Hi Chris,

I've noticed that when I have background rendering switched on, gradually I lose the use of the dials on my Wave Panel.  Normally the background rendering doesn't cause much of a problem with editing on FCPx, but when I'm using the Wave panel with background rendering switched on, the dials gradually stop responding (they don't rise or lower values on FCPx), even though I can manually adjust these dials on screen using the cursor. Once the dials stop working, the only thing that I can do to get them working again is to restart FCPx.  But now I've discovered that if I turn off background rendering, this completely stops the problem of the dials not working.

2013 Mac Pro 3Ghz 8 Core, 
2 x AMD FirePro D700 GPUs, 
64gb RAM,
Mac OSX 10.15.2

FCPx 10.4.8
CP 1.0.5

**Comment by latenitefilms** [comment] 2020-01-13 11:55
Huh - that's really bizarre and interesting. Are you sure it's not just a coincidence? I can't imagine how background rendering would have any impact on anything (unless there's some seriously funky bug in FCPX, which is unlikely).

**Comment by AndrewBrinsmead** [comment] 2020-01-13 22:37
Hi Chris,

I don’t know what the link is, but I found my Wave Panel slowly & consistently stopped responding (I could tweak the dials and nothing would happen), I noticed that it seemed to be happening after a background render was started.  I found that if I turned off background rendering, the problem would stop immediately; when I turn background rendering back on, the problem starts again. So I’ve left background rendering switched off.

Cheers

Andrew

**Comment by AndrewBrinsmead** [comment] 2020-01-15 21:49
BTW, I've been experimenting further with this, and I keep getting the same result: with background render switched on, my Tangent Wave controls gradually take longer & longer to respond (they will work eventually… but the delay becomes so pronounced that the Tangent Wave panel becomes effectively useless).  However, this problem disappears as soon as I turn off background rendering - the Tangent Wave controls respond as expected.

**Comment by latenitefilms** [comment] 2020-01-15 21:56
Well, that is very interesting! I'll try and reproduce here, and see if we can come up with a fix.

**Comment by latenitefilms** [comment] 2020-01-16 11:17
@AndrewBrinsmead - Do you have "Enable Rendering During Playback" ticked within CommandPost's preferences? Does this issue happen when something is literally rendering in the background, or is it still happening if you have a fully rendered timeline, but background render is still enabled?

@randomeizer - Having something render in the background, does trigger some `AXProgressIndicator` notifications, but they're certainly not triggering regularly enough to cause any issues.

```lua
2020-01-16 22:13:16: 22:13:16                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004aa4a78); details: {}
2020-01-16 22:13:18: 22:13:18                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048327e8); details: {}
2020-01-16 22:13:21: 22:13:21                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004aa1048); details: {}
2020-01-16 22:13:22: 22:13:22                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004aac7a8); details: {}
2020-01-16 22:13:24: 22:13:24                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004831d38); details: {}
2020-01-16 22:13:27: 22:13:27                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004adcd18); details: {}
2020-01-16 22:13:29: 22:13:29                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004ac1fd8); details: {}
2020-01-16 22:13:31: 22:13:31                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004af9318); details: {}
2020-01-16 22:13:35: 22:13:35                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000493a728); details: {}
2020-01-16 22:13:37: 22:13:37                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004915f18); details: {}
2020-01-16 22:13:39: 22:13:39                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004ae6e78); details: {}
2020-01-16 22:13:42: 22:13:42                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000483b808); details: {}
2020-01-16 22:13:44: 22:13:44                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004940b08); details: {}
2020-01-16 22:13:46: 22:13:46                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004824208); details: {}
2020-01-16 22:13:49: 22:13:49                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004957dd8); details: {}
2020-01-16 22:13:51: 22:13:51                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048f5f18); details: {}
2020-01-16 22:13:53: 22:13:53                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000049c0058); details: {}
2020-01-16 22:13:55: 22:13:55                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000049700b8); details: {}
2020-01-16 22:13:58: 22:13:58                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000496a698); details: {}
2020-01-16 22:14:00: 22:14:00                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000049c3358); details: {}
2020-01-16 22:14:02: 22:14:02                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000049f4028); details: {}
2020-01-16 22:14:04: 22:14:04                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000498ca18); details: {}
2020-01-16 22:14:06: 22:14:06                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000499b9e8); details: {}
2020-01-16 22:14:08: 22:14:08                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000049982f8); details: {}
2020-01-16 22:14:10: 22:14:10                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000481c058); details: {}
2020-01-16 22:14:12: 22:14:12                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048c1ac8); details: {}
2020-01-16 22:14:14: 22:14:14                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000499b298); details: {}
2020-01-16 22:14:17: 22:14:17                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048e8118); details: {}
2020-01-16 22:14:19: 22:14:19                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004983d48); details: {}
2020-01-16 22:14:21: 22:14:21                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004827508); details: {}
2020-01-16 22:14:23: 22:14:23                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048ef238); details: {}
2020-01-16 22:14:26: 22:14:26                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000049810a8); details: {}
2020-01-16 22:14:28: 22:14:28                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000484ede8); details: {}
2020-01-16 22:14:30: 22:14:30                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000049eff28); details: {}
2020-01-16 22:14:32: 22:14:32                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048fd168); details: {}
2020-01-16 22:14:35: 22:14:35                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048752b8); details: {}
2020-01-16 22:14:36: 22:14:36                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004807e38); details: {}
2020-01-16 22:14:38: 22:14:38                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004804bf8); details: {}
2020-01-16 22:14:41: 22:14:41                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048775c8); details: {}
2020-01-16 22:14:44: 22:14:44                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004875948); details: {}
2020-01-16 22:14:47: 22:14:47                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048106b8); details: {}
2020-01-16 22:14:49: 22:14:49                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048f87d8); details: {}
2020-01-16 22:14:51: 22:14:51                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000482cbf8); details: {}
2020-01-16 22:14:53: 22:14:53                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048126c8); details: {}
2020-01-16 22:14:55: 22:14:55                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048041a8); details: {}
2020-01-16 22:14:57: 22:14:57                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x60000488daf8); details: {}
2020-01-16 22:15:02: 22:15:02                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048a5498); details: {}
2020-01-16 22:15:04: 22:15:04                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048a72f8); details: {}
2020-01-16 22:15:08: 22:15:08                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048a4e98); details: {}
2020-01-16 22:15:10: 22:15:10                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048d1408); details: {}
2020-01-16 22:15:13: 22:15:13                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004845ee8); details: {}
2020-01-16 22:15:15: 22:15:15                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x600004847328); details: {}
2020-01-16 22:15:17: 22:15:17                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048ae308); details: {}
2020-01-16 22:15:20: 22:15:20                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048d7028); details: {}
2020-01-16 22:15:23: 22:15:23                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048d42f8); details: {}
2020-01-16 22:15:25: 22:15:25                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048d6428); details: {}
2020-01-16 22:15:27: 22:15:27                 notification: AXValueChanged; ui: hs._asm.axuielement: AXProgressIndicator (0x6000048b2ab8); details: {}
```

**Comment by latenitefilms** [comment] 2020-01-16 11:25
@randomeizer - Although it seems we do have multiple `cp.ui.notifier`'s all triggering at the same time because of the same notification. We have:

- `cp/app.lua`
- `cp/apple/finalcutpro/viewer/Viewer.lua`
- `cp/ui/StaticText.lua`
- `cp/ui/Windows.lua`

I don't think there's enough notifications being triggered to cause any issues, but I wonder if we clean things up a bit regardless?

**Comment by latenitefilms** [comment] 2021-01-19 21:39
Can't replicate so closing.

**Closed as completed by latenitefilms** 2021-01-19 21:39 UTC
Labels: bug, can't replicate, chris can't solve
