### ISSUE TITLE
Color Wheel - color reset not always work

### ISSUE THREAD

**Issue by lokcheung** [fcpxhacks/fcpxhacks#2975] opened 2022-05-08 17:41 UTC
I'm using a Loupedeck+. When buttons were set to, for example, "Color Wheel - Highlights - Blue Reset", it only reset if the colour was shifted to blue; if the colour was shifted to yellow (basically minus blue) with the "Colour Wheel - Highlights - Blue Down", pressing reset doesn't reset it. This happens to all red/green/blue, and all highlights/midtones/shadows.

**Comment by latenitefilms** [comment] 2022-05-09 02:44
@lokcheung - Firstly, thanks so much for supporting CommandPost - HUGELY appreciated!

I've moved your issue from the LoupedeckPlugin repository, to this repository, because this is where everything related to CommandPost happens - the LoupedeckPlugin repository is a work-in-progress project, where we're trying to make an official Loupedeck Plugin, which I'm hoping to finish off by the end of the month.

As far as I can tell, the action is actually working as intended. The  "Color Wheel - Highlights - Blue Reset" will basically just reset the Color > Blue attribute to 0. If you open up the numerical values for the Color Wheel, you'll get a better sense of what I mean:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/22286696/167331655-6187be98-0044-4598-b31f-16c80a955e9b.png">

I'm going to close this issue for now, but feel free to re-open if anything is unclear.

**Closed as completed by latenitefilms** 2022-05-09 02:44 UTC
Labels: tech support
