### ISSUE TITLE
Console times out when filtering options in Chinese

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#2277] opened 2020-03-11 04:40 UTC
Demonstration from Pozu Tsai, in CommandPost Users group:

https://www.youtube.com/watch?v=uJWE2s8sClU

Followup video with a new user set to English:

https://www.youtube.com/watch?v=rLUJ6PQxYeU

"I'm using traditional Chinese in macOS 10.15.3, and English in Fcpx 10.4.8"

Looks like they may be in Taiwan, based on the the "en_TW" language code in the Error Log.

**Comment by latenitefilms** [comment] 2020-03-11 04:47
Pozu Tsai's **Language & Region** settings:

![a1](https://user-images.githubusercontent.com/22286696/76383318-91841300-63af-11ea-890d-dd583ea2b091.png)
![a2](https://user-images.githubusercontent.com/22286696/76383314-8df08c00-63af-11ea-943b-2999ddd836f3.png)

**Comment by pozu314** [comment] 2020-03-11 04:53
while I'm using my 2018 15' mbpr in macOS 10.14  traditional Chinese setting, I think everything is perfect, but It's happened when I upgrade to 16'mbpr in macOS 10.15

**Comment by latenitefilms** [comment] 2020-03-11 05:01
Here's Pozu Tsai's preferences files & caches:

[CommandPost.zip](https://github.com/CommandPost/CommandPost/files/4316099/CommandPost.zip)

[org.latenitefilms.CommandPost.zip](https://github.com/CommandPost/CommandPost/files/4316101/org.latenitefilms.CommandPost.zip)

Interestingly, the `System Motion Templates.cpCache` files does have some non-English characters inside:

```lua
{
  "en" : [
    {
      "path" : "\/Library\/Application Support\/Final Cut Pro\/Templates.localized\/Effects.localized\/Film Emulation\/FilmConvertPro2",
      "locale" : "en",
      "type" : "videoEffect",
      "category" : "Film Emulation",
      "name" : "FilmConvertPro2"
    },
    {
      "path" : "\/Library\/Application Support\/Final Cut Pro\/Templates.localized\/Transitions.localized\/mTransition Zoom－运动模糊转场\/UR Corner Rotate Up",
      "locale" : "en",
      "name" : "UR Corner Rotate Up",
      "type" : "transition",
      "category" : "mTransition Zoom－运动模糊转场",
      "theme" : "Pre-animated"
    },
    {
      "path" : "\/Library\/Application Support\/Final Cut Pro\/Templates.localized\/Transitions.localized\/mTransition Zoom－运动模糊转场\/Flip Right",
      "locale" : "en",
      "name" : "Flip Right",
      "type" : "transition",
      "category" : "mTransition Zoom－运动模糊转场",
      "theme" : "Pre-animated"
    },
    {
      "path" : "\/Library\/Application Support\/Final Cut Pro\/Templates.localized\/Transitions.localized\/mTransition Zoom－运动模糊转场\/LL Corner Rotate Up",
      "locale" : "en",
      "name" : "LL Corner Rotate Up",
      "type" : "transition",
      "category" : "mTransition Zoom－运动模糊转场",
      "theme" : "Pre-animated"
    },
```

...which may be what's tripping up the Search Console filter?

**Comment by latenitefilms** [comment] 2020-03-11 05:25
Pozu Tsai writes:

> I removed my templates then It’s work at first time but suddenly freeze again...
> 
> https://www.youtube.com/watch?v=iNkgtk5KriU

**Comment by latenitefilms** [comment] 2020-03-11 05:48
Just tested on my machine - it doesn't seem to be related to non-English characters:

<img width="869" alt="Screen Shot 2020-03-11 at 4 46 33 pm" src="https://user-images.githubusercontent.com/22286696/76386185-ee83c700-63b7-11ea-8439-ec2cb7208eb0.png">

I did have one freeze though before this when doing some testing around, which may or may not be related:

```lua
Date/Time:       2020-03-11 16:39:52 +1100
End time:        2020-03-11 16:39:53 +1100
OS Version:      Mac OS X 10.14.6 (Build 18G1012)
Architecture:    x86_64h
Report Version:  28

Data Source:     Stackshots
Shared Cache:    0xc07b000 9096DA91-B13E-3E30-AA41-624A8B1EACCD
Shared Cache:    0 6F48FEBF-7BFE-3CF2-82AB-3CBC77965D92

Command:         CommandPost
Path:            /Users/USER/*/CommandPost.app/Contents/MacOS/CommandPost
Identifier:      org.latenitefilms.CommandPost
Version:         1.0.7-beta.5 (5785)
PID:             89441

Event:           hang
Duration:        1.29s
Steps:           13 (100ms sampling interval)

Hardware model:  MacBookPro14,3
Active cpus:     8

Time Awake Since Boot: 340000s
Time Since Wake: 31000s

Fan speed:       5932 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------


Heaviest stack for the main thread of the target process:
  13  start + 1 (libdyld.dylib + 91093) [0x7fff639bb3d5]
  13  NSApplicationMain + 777 (AppKit + 10952) [0x7fff3500eac8]
  13  -[NSApplication run] + 699 (AppKit + 79240) [0x7fff3501f588]
  13  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361 (AppKit + 103531) [0x7fff3502546b]
  13  _DPSNextEvent + 1135 (AppKit + 108413) [0x7fff3502677d]
  13  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 44150) [0x7fff36c8dc76]
  13  ReceiveNextEventCommon + 603 (HIToolbox + 44773) [0x7fff36c8dee5]
  13  RunCurrentEventLoopInMode + 292 (HIToolbox + 45483) [0x7fff36c8e1ab]
  13  CFRunLoopRunSpecific + 455 (CoreFoundation + 239214) [0x7fff37a2f66e]
  13  __CFRunLoopRun + 2289 (CoreFoundation + 242097) [0x7fff37a301b1]
  13  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9 (CoreFoundation + 244359) [0x7fff37a30a87]
  13  _dispatch_main_queue_callback_4CF + 1135 (libdispatch.dylib + 59021) [0x7fff6397968d]
  13  _dispatch_client_callout + 8 (libdispatch.dylib + 13885) [0x7fff6396e63d]
  13  _dispatch_call_block_and_release + 12 (libdispatch.dylib + 9720) [0x7fff6396d5f8]
  13  __29-[HSToolbar performCallback:]_block_invoke.101 + 633 (toolbar_internal.m:207,13 in toolbar_internal.so + 7502) [0x1115a2d4e]
  13  -[LuaSkin protectedCallAndError:nargs:nresults:] + 55 (Skin.m:262,19 in LuaSkin + 10957) [0x10c34bacd]
  13  -[LuaSkin protectedCallAndTraceback:nresults:] + 203 (Skin.m:251,9 in LuaSkin + 10776) [0x10c34ba18]
  13  lua_pcallk + 236 (lapi.c:969,14 in LuaSkin + 106016) [0x10c362e20]
  13  luaD_pcall + 110 (ldo.c:156,3 in LuaSkin + 132816) [0x10c3696d0]
  13  luai_objcttry + 28 (lobjectivec_exceptions.m:84,3 in LuaSkin + 49106) [0x10c354fd2]
  13  luaD_callnoyield + 21 (ldo.c:526,3 in LuaSkin + 131539) [0x10c3691d3]
  13  luaD_call + 64 (ldo.c:516,5 in LuaSkin + 131474) [0x10c369192]
  13  luaV_execute + 708 (lvm.c:1134,13 in LuaSkin + 115156) [0x10c3651d4]
  13  luaD_precall + 681 (ldo.c:451,11 in LuaSkin + 131108) [0x10c369024]
  5   webview_html + 326 (internal.m:1395,20 in internal.so + 43904) [0x10fbb1b80]
  3   -[WKWebView isLoading] + 28 (WebKit + 1606358) [0x7fff462992d6]
  1   WebKit::PageLoadState::isLoading() const + 34 (WebKit + 1853022) [0x7fff462d565e]


Process:         CommandPost [89441]
UUID:            E9051748-1CCD-3685-B4EF-9BEBBDCD56BB
Path:            /Users/USER/*/CommandPost.app/Contents/MacOS/CommandPost
Architecture:    x86_64
Footprint:       158.71 MB
Start time:      2020-03-11 16:39:52 +1100
End time:        2020-03-11 16:39:53 +1100
Num samples:     13 (1-13)
CPU Time:        1.188s (4.2G cycles, 10.6G instructions, 0.40c/i)
Note:            3 idle work queue threads omitted

  Thread 0xab1e3f           DispatchQueue 1           13 samples (1-13)         priority 46 (base 46)     cpu time 1.188s (4.2G cycles, 10.6G instructions, 0.40c/i)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from mds [83], process received importance donation from WindowServer [215], IO tier 0>
  13  start + 1 (libdyld.dylib + 91093) [0x7fff639bb3d5] 1-13
    13  NSApplicationMain + 777 (AppKit + 10952) [0x7fff3500eac8] 1-13
      13  -[NSApplication run] + 699 (AppKit + 79240) [0x7fff3501f588] 1-13
        13  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361 (AppKit + 103531) [0x7fff3502546b] 1-13
          13  _DPSNextEvent + 1135 (AppKit + 108413) [0x7fff3502677d] 1-13
            13  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 44150) [0x7fff36c8dc76] 1-13
              13  ReceiveNextEventCommon + 603 (HIToolbox + 44773) [0x7fff36c8dee5] 1-13
                13  RunCurrentEventLoopInMode + 292 (HIToolbox + 45483) [0x7fff36c8e1ab] 1-13
                  13  CFRunLoopRunSpecific + 455 (CoreFoundation + 239214) [0x7fff37a2f66e] 1-13
                    13  __CFRunLoopRun + 2289 (CoreFoundation + 242097) [0x7fff37a301b1] 1-13
                      13  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9 (CoreFoundation + 244359) [0x7fff37a30a87] 1-13
                        13  _dispatch_main_queue_callback_4CF + 1135 (libdispatch.dylib + 59021) [0x7fff6397968d] 1-13
                          13  _dispatch_client_callout + 8 (libdispatch.dylib + 13885) [0x7fff6396e63d] 1-13
                            13  _dispatch_call_block_and_release + 12 (libdispatch.dylib + 9720) [0x7fff6396d5f8] 1-13
                              13  __29-[HSToolbar performCallback:]_block_invoke.101 + 633 (toolbar_internal.m:207,13 in toolbar_internal.so + 7502) [0x1115a2d4e] 1-13
                                13  -[LuaSkin protectedCallAndError:nargs:nresults:] + 55 (Skin.m:262,19 in LuaSkin + 10957) [0x10c34bacd] 1-13
                                  13  -[LuaSkin protectedCallAndTraceback:nresults:] + 203 (Skin.m:251,9 in LuaSkin + 10776) [0x10c34ba18] 1-13
                                    13  lua_pcallk + 236 (lapi.c:969,14 in LuaSkin + 106016) [0x10c362e20] 1-13
                                      13  luaD_pcall + 110 (ldo.c:156,3 in LuaSkin + 132816) [0x10c3696d0] 1-13
                                        13  luai_objcttry + 28 (lobjectivec_exceptions.m:84,3 in LuaSkin + 49106) [0x10c354fd2] 1-13
                                          13  luaD_callnoyield + 21 (ldo.c:526,3 in LuaSkin + 131539) [0x10c3691d3] 1-13
                                            13  luaD_call + 64 (ldo.c:516,5 in LuaSkin + 131474) [0x10c369192] 1-13
                                              13  luaV_execute + 708 (lvm.c:1134,13 in LuaSkin + 115156) [0x10c3651d4] 1-13
                                                13  luaD_precall + 681 (ldo.c:451,11 in LuaSkin + 131108) [0x10c369024] 1-13
                                                  1   objc_msgSend + 46 (libobjc.A.dylib + 26286) [0x7fff621de6ae] (running) 1
                                                  1   objc_msgSend + 26 (libobjc.A.dylib + 26266) [0x7fff621de69a] (running) 2
                                                  1   -[WKWebView isLoading] + 0 (WebKit + 1606330) [0x7fff462992ba] (running) 3
                                                  3   webview_html + 326 (internal.m:1395,20 in internal.so + 43904) [0x10fbb1b80] 4-6
                                                    1   -[WKWebView isLoading] + 28 (WebKit + 1606358) [0x7fff462992d6] 4
                                                      1   WebKit::PageLoadState::isLoading() const + 4 (WebKit + 1852992) [0x7fff462d5640] (running) 4
                                                    1   -[WKWebView isLoading] + 23 (WebKit + 1606353) [0x7fff462992d1] (running) 5
                                                    1   -[WKWebView isLoading] + 28 (WebKit + 1606358) [0x7fff462992d6] 6
                                                      1   WebKit::PageLoadState::isLoading() const + 11 (WebKit + 1852999) [0x7fff462d5647] (running) 6
                                                  1   objc_msgSend + 33 (libobjc.A.dylib + 26273) [0x7fff621de6a1] (running) 7
                                                  1   objc_msgSend + 46 (libobjc.A.dylib + 26286) [0x7fff621de6ae] (running) 8
                                                  1   objc_msgSend + 41 (libobjc.A.dylib + 26281) [0x7fff621de6a9] (running) 9
                                                  2   webview_html + 326 (internal.m:1395,20 in internal.so + 43904) [0x10fbb1b80] 10-11
                                                    1   -[WKWebView isLoading] + 28 (WebKit + 1606358) [0x7fff462992d6] 10
                                                      1   WebKit::PageLoadState::isLoading() const + 34 (WebKit + 1853022) [0x7fff462d565e] (running) 10
                                                    1   -[WKWebView isLoading] + 31 (WebKit + 1606361) [0x7fff462992d9] (running) 11
                                                  2   objc_msgSend + 33 (libobjc.A.dylib + 26273) [0x7fff621de6a1] (running) 12-13

  Thread 0xab1e60           Thread name "com.twitter.crashlytics.mac.MachExceptionServer"                 13 samples (1-13)         priority 31 (base 31)
  <thread QoS default (requested default), process unclamped, process received importance donation from mds [83], process received importance donation from WindowServer [215], IO tier 0>
  13  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff63bae40d] 1-13
    13  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff63bb2249] 1-13
      13  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff63baf2eb] 1-13
        13  CLSMachExceptionServer + 107 (CommandPost + 666694) [0x10c0a8c46] 1-13
          13  mach_msg_trap + 10 (libsystem_kernel.dylib + 4650) [0x7fff63af022a] 1-13
           *13  ipc_mqueue_receive_continue + 0 (kernel + 1655600) [0xffffff8000394330] 1-13

  Thread 0xab1ebe           13 samples (1-13)         priority 97 (base 97)
  <process unclamped, process received importance donation from mds [83], process received importance donation from WindowServer [215], IO tier 0>
  13  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff63bae40d] 1-13
    13  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff63bb2249] 1-13
      13  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff63baf2eb] 1-13
        13  CAPThread::Entry(CAPThread*) + 77 (CoreMIDI + 301437) [0x7fff388b197d] 1-13
          13  XThread::RunHelper(void*) + 10 (CoreMIDI + 281332) [0x7fff388acaf4] 1-13
            13  MIDIProcess::RunMIDIInThread() + 333 (CoreMIDI + 190675) [0x7fff388968d3] 1-13
              13  XServerMachPort::ReceiveMessage(int&, void*, int&) + 95 (CoreMIDI + 74725) [0x7fff3887a3e5] 1-13
                13  mach_msg_trap + 10 (libsystem_kernel.dylib + 4650) [0x7fff63af022a] 1-13
                 *13  ipc_mqueue_receive_continue + 0 (kernel + 1655600) [0xffffff8000394330] 1-13

  Thread 0xab1f00           Thread name "com.apple.NSEventThread"               13 samples (1-13)         priority 46 (base 46)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from mds [83], process received importance donation from WindowServer [215], IO tier 0>
  13  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff63bae40d] 1-13
    13  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff63bb2249] 1-13
      13  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff63baf2eb] 1-13
        13  _NSEventThread + 175 (AppKit + 140450) [0x7fff3502e4a2] 1-13
          13  CFRunLoopRunSpecific + 455 (CoreFoundation + 239214) [0x7fff37a2f66e] 1-13
            13  __CFRunLoopRun + 1612 (CoreFoundation + 241420) [0x7fff37a2ff0c] 1-13
              13  __CFRunLoopServiceMachPort + 328 (CoreFoundation + 244126) [0x7fff37a3099e] 1-13
                13  mach_msg_trap + 10 (libsystem_kernel.dylib + 4650) [0x7fff63af022a] 1-13
                 *13  ipc_mqueue_receive_continue + 0 (kernel + 1655600) [0xffffff8000394330] 1-13

  Thread 0xab1fa2           Thread name "JavaScriptCore bmalloc scavenger"      13 samples (1-13)         priority 37 (base 37)
  <thread QoS user initiated (requested user initiated), process unclamped, process received importance donation from mds [83], process received importance donation from WindowServer [215], IO tier 0>
  13  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff63bae40d] 1-13
    13  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff63bb2249] 1-13
      13  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff63baf2eb] 1-13
        13  void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 39 (JavaScriptCore + 2264807) [0x7fff3af15ee7] 1-13
          13  bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 9 (JavaScriptCore + 2258297) [0x7fff3af14579] 1-13
            13  bmalloc::Scavenger::threadRunLoop() + 139 (JavaScriptCore + 2260299) [0x7fff3af14d4b] 1-13
              13  void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 82 (JavaScriptCore + 2243650) [0x7fff3af10c42] 1-13
                13  std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18 (libc++.1.dylib + 35338) [0x7fff60beca0a] 1-13
                  13  __psynch_cvwait + 10 (libsystem_kernel.dylib + 18538) [0x7fff63af386a] 1-13
                   *13  psynch_cvcontinue + 0 (pthread + 19324) [0xffffff7f82e80b7c] 1-13

  Thread 0xab1fa5           Thread name "com.apple.coreanimation.render-server" 13 samples (1-13)         priority 55 (base 55)
  <process unclamped, process received importance donation from mds [83], process received importance donation from WindowServer [215], IO tier 0>
  13  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff63bae40d] 1-13
    13  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff63bb2249] 1-13
      13  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff63baf2eb] 1-13
        13  thread_fun(void*) + 25 (QuartzCore + 403430) [0x7fff425027e6] 1-13
          13  CA::Render::Server::server_thread(void*) + 865 (QuartzCore + 404314) [0x7fff42502b5a] 1-13
            13  mach_msg_trap + 10 (libsystem_kernel.dylib + 4650) [0x7fff63af022a] 1-13
             *13  ipc_mqueue_receive_continue + 0 (kernel + 1655600) [0xffffff8000394330] 1-13

  Thread 0xab1feb           Thread name "com.apple.NSURLConnectionLoader"       13 samples (1-13)         priority 31 (base 31)
  <thread QoS default (requested default), process unclamped, process received importance donation from mds [83], process received importance donation from WindowServer [215], IO tier 0>
  13  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff63bae40d] 1-13
    13  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff63bb2249] 1-13
      13  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff63baf2eb] 1-13
        13  __NSThread__start__ + 1194 (Foundation + 73954) [0x7fff39c8b0e2] 1-13
          13  -[__CoreSchedulingSetRunnable runForever] + 210 (CFNetwork + 316112) [0x7fff369152d0] 1-13
            13  CFRunLoopRunSpecific + 455 (CoreFoundation + 239214) [0x7fff37a2f66e] 1-13
              13  __CFRunLoopRun + 1612 (CoreFoundation + 241420) [0x7fff37a2ff0c] 1-13
                13  __CFRunLoopServiceMachPort + 328 (CoreFoundation + 244126) [0x7fff37a3099e] 1-13
                  13  mach_msg_trap + 10 (libsystem_kernel.dylib + 4650) [0x7fff63af022a] 1-13
                   *13  ipc_mqueue_receive_continue + 0 (kernel + 1655600) [0xffffff8000394330] 1-13
```

**Comment by pozu314** [comment] 2020-03-11 05:58
I found out that when I restart or relogin my mac , It can work a few minutes but still freeze again

**Comment by latenitefilms** [comment] 2020-03-11 10:37
Crash Report from Pozu: 

https://gist.github.com/latenitefilms/9b0de90682c56a996352c1683cf5ac3e

**Comment by latenitefilms** [comment] 2020-03-11 10:50
@asmagill - Sorry to drag you into a CommandPost thread, but would you have any ideas why CommandPost would be freezing based on [this crash report](https://gist.github.com/latenitefilms/9b0de90682c56a996352c1683cf5ac3e)? Looks like something is being caught in an infinite loop after `hs.plist.read()` is used if I'm understanding it correctly?

**Comment by asmagill** [comment] 2020-03-11 13:44
Off the top of my head, I'm not sure... how large of a file are we talking about? What's its contents (mostly text, binary data, etc.)?

Remember LuaSkin shoves everything into lua types almost immediately, so if it's large chunks of text/binary data it *will* be slow. Thats why we rewrote `hs.doc`, were discussing an `hs.json` replacement, and I started `hs.text`.

Is the file it's reading something you can share or that I can download from somewhere and take a look at? It will probably be tonight/tomorrow, so if you can't share it or want to look at it yourself sooner, what I'd probably start with is making a custom `plist_read` that could generate some informational details for me... how many keys, what the value types and sizes are, etc. and if the values are dictionaries, do the same for those but maybe with a level limit to prevent recursing too deeply... plist's aren't supposed to be self-referential (and LuaSkin is supposed to detect that) but just in case.

I'll give it some more thought, but these are my first impressions/thoughts.

**Comment by latenitefilms** [comment] 2020-03-12 00:45
@asmagill - To be honest... I'm not sure. I can't reproduce the hang on any of our machines, so I'm really sure why it's reading a `plist` and this point in time, or why it's hanging. It definitely shouldn't be reading a massive file (you can see the kinds of `plist` CommandPost reads in [this post](https://github.com/CommandPost/CommandPost/issues/2277#issuecomment-597445304)). I guess I was more getting your advice on the crash log itself - to make sure I read it correctly in that the `plist_read` is where it's hanging (as I'm not that savvy at reading crash logs).

We'll do some more testing and experimenting over the coming days.

Thanks heaps for your fast reply - HUGELY appreciated!

**Comment by latenitefilms** [comment] 2020-08-17 15:54
I could never replicate, so I'm going to close this issue for now.

**Closed as completed by latenitefilms** 2020-08-17 15:54 UTC
Labels: bug, chris can't solve, hang
