### ISSUE TITLE
Play/Pause Extremely Laggy with CommandPost Bank with Color Controls (MIDI and Loupedeck)

### ISSUE THREAD

**Issue by pvanleer** [fcpxhacks/fcpxhacks#2359] opened 2020-06-05 15:58 UTC
This is an incredibly random one, but I've noticed it for months. I'm not sure on a process level why this is, BUT I've noticed it with my midi controller as well as the Loupedeck CT, and the issue goes away as soon as I quit Command Post. Whenever I am color grading a project and have a Command Post bank with color actions assigned, the play/pause action is on a 4-5 second delay. It plays fine, but then to pause takes 4-5 seconds after you click it, sometimes it just goes unnoticed and never pauses. Odd thing is it acts this way when tapping the keyboard spacebar as well. I'm not sure if it's "color grading" specific/tied to those color grading actions, or if it's more tied to when the computer is rendering something, but it seems that whatever it is Command Post gets hung up with pausing (midi, CT, and keyboard). As soon as I quit CP, the keyboard works again no lag. Let me know how I can help, I know this one is strange.

**Comment by latenitefilms** [comment] 2020-08-11 05:53
@pvanleer - Are you still seeing this issue? What colour actions are you using exactly?

**Comment by pvanleer** [comment] 2020-08-11 22:10
Thanks for the comment and question! Unfortunately, even with the .13 beta this is still an issue. It basically happens anytime I have CP open and have a color grade applied. Play/Pause work again immediately after I close CP.

**Comment by latenitefilms** [comment] 2020-08-11 22:37
Any chance you could record a screen recording demonstrating? Start with both FCPX and CP quit, then demonstrate opening both apps and reproduce the issue.

**Comment by pvanleer** [comment] 2020-08-12 17:27
Sorry for the delay! Here's the screen recording. Let me know if there's anything else I can do to help :) 

https://drive.google.com/open?id=1wQ4kolj-YkcqbfsF6J7nMkwtByrZqr7k&authuser=hello%40prescottvanleer.com&usp=drive_fs

**Comment by latenitefilms** [comment] 2020-08-13 15:18
Thanks for the detailed video! HUGELY appreciated!

Well... it's certainly a bizarre and annoying bug.

_(Unrelated - that weird slow startup time is also very strange. I've never seen startup times that slow, even on massive projects we've got - such as feature films or TV series. We also have older 5K iMac's in the office, so I don't think it's the machine at fault. You mention spinning drives, but if the library is on SSDs, it shouldn't really be loading anything on startup?)_

What action in CommandPost are you using with the Loupedeck to play/pause? There's a few "Play" actions, but you can also just use a spacebar virtual keypress. Have you tried different ones to see if they have any impact?

<img width="869" alt="Screen Shot 2020-08-14 at 12 42 28 am" src="https://user-images.githubusercontent.com/22286696/90149048-64f17e80-ddc7-11ea-81ef-33519737c0d9.png">

<img width="869" alt="Screen Shot 2020-08-14 at 12 42 21 am" src="https://user-images.githubusercontent.com/22286696/90148754-0e844000-ddc7-11ea-90c3-c987ab34e355.png">

Also, do you have any other control surfaces enabled - such as the Touch Bar?

Can you take a screenshot of the "Final Cut Pro" panel in CommandPost Preferences?

FWIW - I have found a bug in the "Play" command action - it doesn't actually do anything, nor does the "Pause" action. Will fix those in a seperate issue.

**Comment by latenitefilms** [comment] 2020-08-13 15:42
Could you also please email me your CommandPost settings/preferences found in this folder:

`~/Library/Application Support/CommandPost`

Remind me... Are you using a Loupedeck+ or a Loupedeck CT? If you're using a Loupedeck+, did you originally set it up in the MIDI Preferences panel, before we had a Loupedeck+ Preferences panel?

**Comment by pvanleer** [comment] 2020-08-13 15:53
Thanks for the info! I'm using the Loupedeck CT. I never had the Loupedeck+, so everything was setup for the CT. I did use a midi controller previously (Traktor Kontrol X1 MkII) and had a setup for that. For the Library/Application Support/CommandPost request, do you want that whole folder? There's no specific settings or preferences folder within that.

On to the play/pause issue: I have been using Play/Pause. But I did just try the Space action and believe it or not, that seems to work properly on the CT and keyboard! I swore I've tried using Space before in the past and it didn't work, but maybe I'm mistaken. So that's progress! I was thinking that since the keyboard itself acts the same way with the space bar, there's something outside of the specific CP action that is tripping it up? I had experienced this issue when I was using the Midi controller as well. This happens whether another control surface is enabled or not. 

That's good to hear that you've discovered something up with the Play command action! I do believe I noticed that it didn't pause, but I thought maybe that was the intention.

I've attached a screenshot of the FCP panel below! Please let me know what you think and I'll get back to you asap!

![Screen Shot 2020-08-13 at 8 40 15 AM](https://user-images.githubusercontent.com/54328549/90155828-9ecb7200-dd40-11ea-9d62-69ecde4e7ed8.png)


Sidebar: It is something that only really got bad in the last year or so. It's definitely much faster when I eject the spinning drives and use only the SSD - my main SSD is just for editing and the library and all files are located on the SSD for speed. Even with that it's slow to startup unless I eject all other spinning drives. Not quite sure what I may have done or what else might be happening, but it's definitely slower than it used to be generally. Once it's open it's fine. I am using a TB3 hub and I'm saving my backups to Google Drive, so perhaps there's something to do with that involved. Anyway, perhaps I should look more into it!

**Comment by latenitefilms** [comment] 2020-08-13 16:04
> I'm using the Loupedeck CT. I never had the Loupedeck+, so everything was setup for the CT.

Great, thanks!

> I did use a midi controller previously (Traktor Kontrol X1 MkII) and had a setup for that.

Are those settings still there in CommandPost?

> For the Library/Application Support/CommandPost request, do you want that whole folder? There's no specific settings or 
preferences folder within that.

Yes, if you could ZIP up the whole folder, that would be great. There should be a bunch of sub-folders that look like this:

<img width="364" alt="Screen Shot 2020-08-14 at 1 58 38 am" src="https://user-images.githubusercontent.com/22286696/90157927-b0a92580-ddd1-11ea-9788-2ebb6346dbfe.png">

(Note that the ~ means your user folder, i.e. `/Users/*username*/Library/Application Support/CommandPost`)

> I was thinking that since the keyboard itself acts the same way with the space bar, there's something outside of the specific CP action that is tripping it up? I had experienced this issue when I was using the Midi controller as well. This happens whether another control surface is enabled or not.

Something in our code is obviously holding things up - I'm just not sure what it is, as I can't reproduce the bug here. It'll most likely be a feature that's "watching" something in FCPX - i.e. with our scrolling timeline feature, we're constantly watching for the playhead to move.

Interestingly... the "Play" and "Pause" command actions definitely should have done anything - as there was a bug in the code, that would prevent them from doing anything at all. So I'm assuming you were using the "Play" keyboard shortcut?

> Sidebar: It is something that only really got bad in the last year or so. It's definitely much faster when I eject the spinning drives and use only the SSD - my main SSD is just for editing and the library and all files are located on the SSD for speed. Even with that it's slow to startup unless I eject all other spinning drives. Not quite sure what I may have done or what else might be happening, but it's definitely slower than it used to be generally. Once it's open it's fine. I am using a TB3 hub and I'm saving my backups to Google Drive, so perhaps there's something to do with that involved. Anyway, perhaps I should look more into it!

Have you tried trashing your FCPX Preferences?

**Comment by pvanleer** [comment] 2020-08-13 16:31
> Are those (Midi) settings still there in CommandPost?
> 
Yes they are :) 

> Yes, if you could ZIP up the whole folder, that would be great. There should be a bunch of sub-folders that look like this:
> 
Perfect, uploading now and will be in the folder at this link: https://drive.google.com/open?id=1wQ4kolj-YkcqbfsF6J7nMkwtByrZqr7k&authuser=hello%40prescottvanleer.com&usp=drive_fs
> 

> Something in our code is obviously holding things up - I'm just not sure what it is, as I can't reproduce the bug here. It'll most likely be a feature that's "watching" something in FCPX - i.e. with our scrolling timeline feature, we're constantly watching for the playhead to move.
> 
Yeah, makes sense! I'm not sure at all what's up. Hopefully the zip will help reproduce it. Check out below...

> Interestingly... the "Play" and "Pause" command actions definitely should have done anything - as there was a bug in the code, that would prevent them from doing anything at all. So I'm assuming you were using the "Play" keyboard shortcut?
> 
Yeah, I might have. Ok, here's something weird, just so you have all the info. I just tested all the various "Play" options (menu ones and custom ones you've made), and they all play just fine, but do have the pause lag - including the SPACE function this time. With both the CT and keyboard. The consistent thing I have noticed is that when FCPX is rendering a chunk of footage in the timeline (which obviously is often), this happens. So RAM/Memory is a thought I had, but the computer isn't exactly lacking in that area. The SPACE function worked for me in my last comment, but no longer is - I added a preset to all the clips in my timeline (Color Wheels, FilmConvert, LUT, nothing crazy). So obviously there's something else at play. But regardless, it works again just fine once I close CP. Here's my iMac specs, just so you have that info, although I doubt it's an issue with that. FCPX is up to date as well.

![Screen Shot 2020-08-13 at 9 27 24 AM](https://user-images.githubusercontent.com/54328549/90160884-359b2d00-dd47-11ea-9cd9-c76d5d45a4ea.png)

>
> > Sidebar: It is something that only really got bad in the last year or so. It's definitely much faster when I eject the spinning drives and use only the SSD - my main SSD is just for editing and the library and all files are located on the SSD for speed. Even with that it's slow to startup unless I eject all other spinning drives. Not quite sure what I may have done or what else might be happening, but it's definitely slower than it used to be generally. Once it's open it's fine. I am using a TB3 hub and I'm saving my backups to Google Drive, so perhaps there's something to do with that involved. Anyway, perhaps I should look more into it!
> 
> Have you tried trashing your FCPX Preferences?

I haven't....I didn't know there was a way to do that? If that within FCPX somewhere?

**Comment by latenitefilms** [comment] 2020-08-13 16:44
> Perfect, uploading now and will be in the folder at this link: https://drive.google.com/open?id=1wQ4kolj-YkcqbfsF6J7nMkwtByrZqr7k&authuser=hello%40prescottvanleer.com&usp=drive_fs

Awesome, thanks!

> Ok, here's something weird, just so you have all the info. I just tested all the various "Play" options (menu ones and custom ones you've made), and they all play just fine, but do have the pause lag - including the SPACE function this time. With both the CT and keyboard. The consistent thing I have noticed is that when FCPX is rendering a chunk of footage in the timeline (which obviously is often), this happens.

If you quit CommandPost, then re-open it and make sure you only use the "SPACE" action (i.e. the space bar virtual keyboard press action), do you still have issues? I'm guessing it's one action on that you're using somewhere that's causing the issue. Did you apply the preset to your clips with CommandPost and/or the Loupedeck CT? What CommandPost actions did trigger before the play/pause delay came back?

> I haven't....I didn't know there was a way to do that? If that within FCPX somewhere?

Hold down OPTION+COMMAND when you launch FCPX from the dock.

**Comment by pvanleer** [comment] 2020-08-13 17:13
Ok, I tried with the SPACE action and then closing CP and reopening. Same behavior as described above. 

BUT, you ready for something else? So, I have 3 monitors. My iMac for browser and videos scopes, an Ultrawide for the timeline and inspector, and a more color accurate monitor as AV out. I JUST noticed this since I've done those screen recordings for you(!): This issue is only happening when I have video scopes open on my second monitor (the iMac in this case)! When I turn off the scopes, it goes away. When I only use the ultrawide (turn off dual monitors) and have the video scopes open on the ultrawide, it goes away. When I close CP and keep the scopes on the second monitor, it goes away. What the heck could that mean?

**Comment by latenitefilms** [comment] 2020-08-13 17:22
Interesting... I'll try and reproduce tomorrow.

**Comment by pvanleer** [comment] 2020-08-13 17:25
Ok.....Just did that option+command thing to delete preferences. It deleted my workspaces and then I put the scopes on the second monitor. NO ISSUES. Then I added back in the previously saved workspaces and used the scopes on the second monitor....problem is back. Ridiculous. So, I guess I'm just going to start over with the workspaces. Dude, makes no sense.

**Comment by latenitefilms** [comment] 2020-08-13 17:29
Try trashing your preferences again, and instead of using the previously saved workspaces, create them again from scratch.

**Comment by latenitefilms** [comment] 2020-08-13 17:30
We have seen issues in the past where if you use custom workspaces created in an old version of FCPX and use them on a newer version, FCPX can do weird things.

**Comment by pvanleer** [comment] 2020-08-13 17:31
Oh wow, ok I'll do that and report back!

**Comment by latenitefilms** [comment] 2020-08-17 14:49
Did creating new workspaces have any impact?

**Comment by pvanleer** [comment] 2020-08-17 15:53
Sorry for the delay. Just checked it out and yes, it does seem like that was it. So random, but so glad the round about solution was found. Is that a FCPX bug or CP bug/do you think I'll have to remake my workspaces with each FCPX update?

**Comment by latenitefilms** [comment] 2020-08-17 15:56
It's definitely a FCPX bug, but it only seems to affect CommandPost. We've tried to reach out to Apple to solve, but never got a response. Hopefully they silently fix it in the next update.

I'm going to close this issue for now, as it sounds like it's now solved.

**Closed as completed by latenitefilms** 2020-08-17 15:56 UTC
Labels: bug
